global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'chat-service'
    static_configs:
      - targets: ['chat-service:3001']
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3003']

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []  # Aucun alertmanager configuré, mais structure présente