global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'chat-service'
    static_configs:
      - targets: ['chat-service:3001']
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3003']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'
    basic_auth:
      username: '${LOGSTASH_USERNAME}'
      password: '${LOGSTASH_PASSWORD}'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []  # Aucun alertmanager configuré, mais structure présente